spring:
  profile: test
  application:
    name: programmers spring assignments
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:spring_assignments;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: tester
    password: 1234
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  sql:
    init:
      schema-locations: classpath*:schema-h2.sql
      data-locations: classpath*:data-h2.sql
      platform: h2
  main:
    allow-circular-references: true
server:
  port: 5000
jwt:
  token:
    header: X-PRGRMS-AUTH
    issuer: programmers
    client-secret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expiry-seconds: 0
