spring:
  profile: test
  application:
    name: programmers spring assignments
  messages:
    basename: i18n/messages
    encoding: UTF-8 # (기본값) 생략 무방
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console # (기본값) 생략 무방
      settings:
        trace: false  # (기본값) 생략 무방
        web-allow-others: false # (기본값) 생략 무방
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:spring_assignments;MODE=MYSQL;DB_CLOSE_DELAY=-1;
    username: tester
    password: 1234
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
    schema: classpath:schema-h2.sql  # 미지정 시, resource 내의 schema.sql을 기본으로 인식
    # data: classpath:data-h2.sql  # 미지정 시, resource 내의 schema.sql을 기본으로 인식
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
server:
  port: 8080 # (기본값) 생략 무방
jwt:
  token:
    header: X-PRGRMS-AUTH
    issuer: programmers
    client-secret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expiry-seconds: 0
